### ISSUE TITLE
windows下跑的很慢，但跑起来了

### ISSUE THREAD

**Issue by Spr-Peach** [Fanghua-Yu/SUPIR#108]
先按照[#11](https://github.com/Fanghua-Yu/SUPIR/issues/11)中[MatthewK78](https://github.com/MatthewK78)的说明修改requirements.txt，然后根据存放模型的路径修改CKPT_PTH.py和SUPIR_v0.yaml文件，例如我要将模型存放在项目根目录下新建的models文件夹内：
修改CKPT_PTH.py：
```python
LLAVA_CLIP_PATH = './models/clip-vit-large-patch14-336'
LLAVA_MODEL_PATH = './models/llava-v1.5-13b'
SDXL_CLIP1_PATH = './models/clip-vit-large-patch14'
SDXL_CLIP2_CKPT_PTH = './models/open_clip_pytorch_model.bin'
``` 
修改./option/SUPIR_v0.yaml(约152行开始):
```
SDXL_CKPT: './models/sd_xl_base_1.0_0.9vae.safetensors'
SUPIR_CKPT_F: './models/SUPIR-v0F.ckpt'
SUPIR_CKPT_Q: './models/SUPIR-v0Q.ckpt'
SUPIR_CKPT: ~
```
models文件夹如下：
![2](https://github.com/Fanghua-Yu/SUPIR/assets/124544885/287f2df7-ebf9-4fd8-a9a9-cb62b39b0926)

[clip-vit-large-patch14](https://huggingface.co/openai/clip-vit-large-patch14)、[clip-vit-large-patch14-336](https://huggingface.co/openai/clip-vit-large-patch14-336)和[llava-v1.5-13b](https://huggingface.co/liuhaotian/llava-v1.5-13b)如果已经安装过git lfs可以从huggingface上直接git clone，然后下载[open_clip_pytorch_model.bin](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/resolve/main/open_clip_pytorch_model.bin?download=true)和[sd_xl_base_1.0_0.9vae.safetensors](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0_0.9vae.safetensors?download=true)，最后从[Google drive](https://drive.google.com/drive/folders/1yELzm5SvAi9e7kPcO_jPp2XkTs4vK6aR)下载SUPIR-v0F.ckpt和SUPIR-v0Q.ckpt，总共3个文件夹和4个文件放入models下。

**Comment by CuddleSabe** [comment]
SDXL_CLIP2_CKPT_PTH = './models/open_clip_pytorch_model.bin'
根本就是无用的，，他们根本没有用到vit的任何参数来加载controlnet
不知道为什么他们要在论文里说用到vit并在加载函数里面加上这个。。实际没有起到任何作用

**Comment by ganjunhong** [comment]
您好，请教下，现存这个，您是怎么控制在8G内呢

**Comment by jiehwa** [comment]
你好，请问下你的电脑是什么配置？这个4090能跑吗，我看硬件要求60G的显存

**Comment by Trendymen** [comment]
You guys can't use ComfyUI?

**Comment by CuddleSabe** [comment]
> You guys can't use ComfyUI-SUPIR?

那里面太多实现错误了

**Comment by Spr-Peach** [comment]
> 您好，请教下，现存这个，您是怎么控制在8G内呢

好像只能添加 --no_llava，看[#65](https://github.com/Fanghua-Yu/SUPIR/issues/65)

**Comment by HHR-learner** [comment]
你好，我照着改了requirement，所有依赖下载完后运行demo出现这个报错，请问这个如何解决呢
`(SUPIR) user@TITAN2-Cleos-TITAN-RTX-24x2:/media/4TB2/HHR/SUPIR$ CUDA_VISIBLE_DEVICES=0,1 python gradio_demo.py --ip 0.0.0.0 --port 6688 --use_image_slider --log_history
/home/user/anaconda3/envs/SUPIR/lib/python3.8/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/home/user/anaconda3/envs/SUPIR/lib/python3.8/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "gradio_demo.py", line 6, in <module>
    from SUPIR.util import HWC3, upscale_image, fix_resize, convert_dtype
  File "/media/4TB2/HHR/SUPIR/SUPIR/util.py", line 8, in <module>
    from sgm.util import instantiate_from_config
  File "/media/4TB2/HHR/SUPIR/sgm/__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "/media/4TB2/HHR/SUPIR/sgm/models/__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "/media/4TB2/HHR/SUPIR/sgm/models/autoencoder.py", line 12, in <module>
    from ..modules.diffusionmodules.model import Decoder, Encoder
  File "/media/4TB2/HHR/SUPIR/sgm/modules/__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "/media/4TB2/HHR/SUPIR/sgm/modules/encoders/modules.py", line 5, in <module>
    import kornia
  File "/home/user/anaconda3/envs/SUPIR/lib/python3.8/site-packages/kornia/__init__.py", line 8, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "/home/user/anaconda3/envs/SUPIR/lib/python3.8/site-packages/kornia/x/__init__.py", line 2, in <module>
    from .trainer import Trainer
  File "/home/user/anaconda3/envs/SUPIR/lib/python3.8/site-packages/kornia/x/trainer.py", line 11, in <module>
    from accelerate import Accelerator
  File "/home/user/.local/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/user/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/user/.local/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/user/.local/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/home/user/.local/lib/python3.8/site-packages/accelerate/utils/launch.py", line 28, in <module>
    from ..utils.other import merge_dicts
  File "/home/user/.local/lib/python3.8/site-packages/accelerate/utils/other.py", line 28, in <module>
    from deepspeed import DeepSpeedEngine
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 16, in <module>
    from . import module_inject
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/module_inject/replace_module.py", line 732, in <module>
    from ..pipe import PipelineModule
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/config.py", line 28, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 601, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 603, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/home/user/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 115, in get_config_default
    assert not config.__fields__.get(
AttributeError: 'FieldInfo' object has no attribute 'required'`

**Comment by ZhenyanSun** [comment]
有人能分享下 SUPIR的两个ckpt吗？ 目前google driver 地址好像失效了

**Comment by juewangdelty** [comment]
按你的教程走出现了以下错误
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /media/caj/TEN/YJ/SUPIR-master/gradio_demo.py:44 in │
│ │
│ 41 │ raise ValueError('Currently support CUDA only.') │
│ 42 │
│ 43 # load SUPIR │
│ ❱ 44 model, default_setting = create_SUPIR_model(args.opt, SUPIR_sign='Q', │
│ 45 if args.loading_half_params: │
│ 46 │ model = model.half() │
│ 47 if args.use_tile_vae: │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/SUPIR/util.py:36 in create_SUPIR_model │
│ │
│ 33 │
│ 34 def create_SUPIR_model(config_path, SUPIR_sign=None, load_default_sett │
│ 35 │ config = OmegaConf.load(config_path) │
│ ❱ 36 │ model = instantiate_from_config(config.model).cpu() │
│ 37 │ print(f'Loaded model config from [{config_path}]') │
│ 38 │ if config.SDXL_CKPT is not None: │
│ 39 │ │ model.load_state_dict(load_state_dict(config.SDXL_CKPT), stric │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/sgm/util.py:175 in instantiate_from_config │
│ │
│ 172 │ │ elif config == "is_unconditional": │
│ 173 │ │ │ return None │
│ 174 │ │ raise KeyError("Expected key target to instantiate.") │
│ ❱ 175 │ return get_obj_from_str(config["target"])(**config.get("params", d │
│ 176 │
│ 177 │
│ 178 def get_obj_from_str(string, reload=False, invalidate_cache=True): │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/SUPIR/models/SUPIR_model.py:14 in init │
│ │
│ 11 │
│ 12 class SUPIRModel(DiffusionEngine): │
│ 13 │ def init(self, control_stage_config, ae_dtype='fp32', diffusio │
│ ❱ 14 │ │ super().init(*args, **kwargs) │
│ 15 │ │ control_model = instantiate_from_config(control_stage_config) │
│ 16 │ │ self.model.load_control_model(control_model) │
│ 17 │ │ self.first_stage_model.denoise_encoder = copy.deepcopy(self.fi │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/sgm/models/diffusion.py:61 in init │
│ │
│ 58 │ │ │ if sampler_config is not None │
│ 59 │ │ │ else None │
│ 60 │ │ ) │
│ ❱ 61 │ │ self.conditioner = instantiate_from_config( │
│ 62 │ │ │ default(conditioner_config, UNCONDITIONAL_CONFIG) │
│ 63 │ │ ) │
│ 64 │ │ self.scheduler_config = scheduler_config │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/sgm/util.py:175 in instantiate_from_config │
│ │
│ 172 │ │ elif config == "is_unconditional": │
│ 173 │ │ │ return None │
│ 174 │ │ raise KeyError("Expected key target to instantiate.") │
│ ❱ 175 │ return get_obj_from_str(config["target"])(**config.get("params", d │
│ 176 │
│ 177 │
│ 178 def get_obj_from_str(string, reload=False, invalidate_cache=True): │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/sgm/modules/encoders/modules.py:89 in │
│ init │
│ │
│ 86 │ │ super().init() │
│ 87 │ │ embedders = [] │
│ 88 │ │ for n, embconfig in enumerate(emb_models): │
│ ❱ 89 │ │ │ embedder = instantiate_from_config(embconfig) │
│ 90 │ │ │ assert isinstance( │
│ 91 │ │ │ │ embedder, AbstractEmbModel │
│ 92 │ │ │ ), f"embedder model {embedder.class.name} has to │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/sgm/util.py:175 in instantiate_from_config │
│ │
│ 172 │ │ elif config == "is_unconditional": │
│ 173 │ │ │ return None │
│ 174 │ │ raise KeyError("Expected key target to instantiate.") │
│ ❱ 175 │ return get_obj_from_str(config["target"])(**config.get("params", d │
│ 176 │
│ 177 │
│ 178 def get_obj_from_str(string, reload=False, invalidate_cache=True): │
│ │
│ /media/caj/TEN/YJ/SUPIR-master/sgm/modules/encoders/modules.py:462 in │
│ init │
│ │
│ 459 │ ): # clip-vit-base-patch32 │
│ 460 │ │ super().init() │
│ 461 │ │ assert layer in self.LAYERS │
│ ❱ 462 │ │ self.tokenizer = CLIPTokenizer.from_pretrained(version if SDX │
│ 463 │ │ self.transformer = CLIPTextModel.from_pretrained(version if S │
│ 464 │ │ self.device = device │
│ 465 │ │ self.max_length = max_length │
│ │
│ /home/caj/anaconda3/envs/Diff4R/lib/python3.8/site-packages/transformers/tok │
│ enization_utils_base.py:1770 in from_pretrained │
│ │
│ 1767 │ │ │ │ elif is_remote_url(file_path): │
│ 1768 │ │ │ │ │ resolved_vocab_files[file_id] = download_url(file │
│ 1769 │ │ │ else: │
│ ❱ 1770 │ │ │ │ resolved_vocab_files[file_id] = cached_file( │
│ 1771 │ │ │ │ │ pretrained_model_name_or_path, │
│ 1772 │ │ │ │ │ file_path, │
│ 1773 │ │ │ │ │ cache_dir=cache_dir, │
│ │
│ /home/caj/anaconda3/envs/Diff4R/lib/python3.8/site-packages/transformers/uti │
│ ls/hub.py:409 in cached_file │
│ │
│ 406 │ user_agent = http_user_agent(user_agent) │
│ 407 │ try: │
│ 408 │ │ # Load from URL or cache if already cached │
│ ❱ 409 │ │ resolved_file = hf_hub_download( │
│ 410 │ │ │ path_or_repo_id, │
│ 411 │ │ │ filename, │
│ 412 │ │ │ subfolder=None if len(subfolder) == 0 else subfolder, │
│ │
│ /home/caj/anaconda3/envs/Diff4R/lib/python3.8/site-packages/huggingface_hub/ │
│ utils/_validators.py:106 in inner_fn │
│ │
│ 103 │ │ │ kwargs.items(), # Kwargs values │
│ 104 │ │ ): │
│ 105 │ │ │ if arg_name in ["repo_id", "from_id", "to_id"]: │
│ ❱ 106 │ │ │ │ validate_repo_id(arg_value) │
│ 107 │ │ │ │
│ 108 │ │ │ elif arg_name == "token" and arg_value is not None: │
│ 109 │ │ │ │ has_token = True │
│ │
│ /home/caj/anaconda3/envs/Diff4R/lib/python3.8/site-packages/huggingface_hub/ │
│ utils/validators.py:160 in validate_repo_id │
│ │
│ 157 │ │ ) │
│ 158 │ │
│ 159 │ if not REPO_ID_REGEX.match(repo_id): │
│ ❱ 160 │ │ raise HFValidationError( │
│ 161 │ │ │ "Repo id must use alphanumeric chars or '-', '', '.', '-- │
│ 162 │ │ │ " forbidden, '-' and '.' cannot start or end the name, max │
│ 163 │ │ │ f" '{repo_id}'." │
╰──────────────────────────────────────────────────────────────────────────────╯
HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--'
and '..' are forbidden, '-' and '.' cannot start or end the name, max length is
96: ''.
ununtu系统
