### ISSUE TITLE
Can't get test.py to run

### ISSUE THREAD

**Issue by ccoltman** [Fanghua-Yu/SUPIR#126]
Running in the Gradio demo works fine, but trying to run test.py from the command line always gives this:

```
Traceback (most recent call last):
  File "D:\SUPIR\SUPIR\test.py", line 55, in <module>
    model = create_SUPIR_model('options/SUPIR_v0.yaml', supir_sign=args.SUPIR_sign).to(SUPIR_device)
  File "D:\SUPIR\SUPIR\SUPIR\util.py", line 50, in create_SUPIR_model
    model = instantiate_from_config(config.model)
  File "D:\SUPIR\SUPIR\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\SUPIR\SUPIR\SUPIR\models\SUPIR_model.py", line 18, in __init__
    super().__init__(*args, **kwargs)
  File "D:\SUPIR\SUPIR\sgm\models\diffusion.py", line 57, in __init__
    instantiate_from_config(sampler_config)
  File "D:\SUPIR\SUPIR\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\SUPIR\SUPIR\sgm\util.py", line 179, in get_obj_from_str
    module, cls = string.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Is there a way to debug SUPIR so I can see what the command is? If it works in the gradio demo but not in the test.py, I must be missing something important.

My issued command right now is:

`python test.py --img_dir 'D:\SUPVR\frames' --save_dir "D:\SUPVR\upscaled_frames" --SUPIR_sign Q --upscale 2`

**Comment by sonigeez** [comment]
facing same issue
