### ISSUE TITLE
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1)

### ISSUE THREAD

**Issue by goometasoft** [Fanghua-Yu/SUPIR#145]
```
1024x1024 -> 2048x2048 

python test.py \
--img_dir  /SUPIR/test/input  \
--save_dir /SUPIR/test/output \
--SUPIR_sign Q --upscale 2

Traceback (most recent call last):
  File "/SUPIR/wsl_121/test.py", line 98, in <module>
    samples = model.batchify_sample(LQ_img, captions, num_steps=args.edm_steps, restoration_scale=args.s_stage1, s_churn=args.s_churn,
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  
  File "/SUPIR/wsl_121/SUPIR/models/SUPIR_model.py", line 121, in batchify_sample
    c, uc = self.prepare_condition(_z, p, p_p, n_p, N)
  
  File "/SUPIR/wsl_121/SUPIR/models/SUPIR_model.py", line 166, in prepare_condition
    c, uc = self.conditioner.get_unconditional_conditioning(batch, batch_uc)
  
  File "/SUPIR/wsl_121/sgm/modules/encoders/modules.py", line 185, in get_unconditional_conditioning
    c = self(batch_c)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  
  File "/SUPIR/wsl_121/sgm/modules/encoders/modules.py", line 206, in forward
    emb_out = embedder(batch[embedder.input_key])
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  
  File "/SUPIR/wsl_121/sgm/util.py", line 59, in do_autocast
    return f(*args, **kwargs)
  
  File "/SUPIR/wsl_121/sgm/modules/encoders/modules.py", line 560, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  
  File "/SUPIR/wsl_121/sgm/modules/encoders/modules.py", line 572, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  
  File "/SUPIR/wsl_121/sgm/modules/encoders/modules.py", line 604, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  
  File "/opt/conda/envs/cuda121/lib/python3.9/site-packages/torch/nn/functional.py", line 5318, in multi_head_attention_forward
    
	raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")

RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
```

**Comment by shengxiao-zhou** [comment]
Hello, I encountered the same problem, how did you solve it?

**Comment by Qian-CV** [comment]
> Hello, I encountered the same problem, how did you solve it?

you should confirm your Transformer's version

**Comment by shengxiao-zhou** [comment]
> > Hello, I encountered the same problem, how did you solve it?
> 
> you should confirm your Transformer's version

Thanks， problem has been solved！

**Comment by CodeZ1LLa** [comment]
> you should confirm your Transformer's version

How can it be done?

**Comment by javierabad01** [comment]
> > Hello, I encountered the same problem, how did you solve it?
> 
> you should confirm your Transformer's version

Same error here, my Transformer's version is 4.28.1, so is the same as in the requirements. What do you mean by confirm Transformer's version?

**Comment by qianx77** [comment]
I solve the problem.  Not only do you need to confirm the transformer version, but you need to confirm that the open-clip-torch version is not too high
