### ISSUE TITLE
Hello. here is the error message at opening. using latest PINOKIO, win 11. latest update done, 256gig RAM, and 4 Gpu in the system Nvidia A5000

### ISSUE THREAD

**Issue by zeeyannosse** [Fanghua-Yu/SUPIR#147]
Hello Bravo For your tool and work on it !
was very pleased to use it , and after pinokio update recently...   seems a bit on a buggy side of the road if that make any sens ...
did several reset and re-install ... 
allways this error message at the start of the session in red on the top right corner with this kind of "TIMER" then the message pops out...

error
Unexpected token 'I', "Internal S"... is not valid JSON

and here in the terminal  more  infos about the error 👍 
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\dependencies\utils.py", line 813, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
    return [
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema      
    schema = self._generate_schema_inner(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema   
    schema = self._apply_annotations(source_type, annotations)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations  
    schema = get_inner_schema(source_type)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__     
    schema = self._handler(source_type)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__     
    schema = self._handler(source_type)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler       
    schema = self._generate_schema_inner(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type 
    return self._union_schema(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema       
    choices.append(self.generate_schema(arg))
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema      
    schema = self._generate_schema_inner(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema 
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion. 

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\dependencies\utils.py", line 813, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
    return [
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema      
    schema = self._generate_schema_inner(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema   
    schema = self._apply_annotations(source_type, annotations)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations  
    schema = get_inner_schema(source_type)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__     
    schema = self._handler(source_type)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__     
    schema = self._handler(source_type)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler       
    schema = self._generate_schema_inner(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type 
    return self._union_schema(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema       
    choices.append(self.generate_schema(arg))
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema      
    schema = self._generate_schema_inner(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "D:\pinokio\api\supir.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema 
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion. 

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

**Comment by zeeyannosse** [comment]
just as i was going through the error message got this link suggestion ...  sorry I am on the "user side", absolutly no coder ... too bad..  well this is for your information ;)) > just reporting the situation ;))..  I wish you the best to all the dev team ;)). cheers!

 https://docs.pydantic.dev/2.9/errors/usage_errors/#validator-input-type

**Comment by robbsaber** [comment]
Same errors..

**Comment by FurkanGozukara** [comment]
that is why standalone venv is best

still working perfect

https://youtu.be/OYxVEvDf284

### [**Complete Guide to SUPIR Enhancing and Upscaling Images Like in Sci-Fi Movies on Your PC**](https://youtu.be/OYxVEvDf284)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/mfxA2WEIFBtIN7_J_LKZn.png)](https://youtu.be/OYxVEvDf284)

**Comment by ai-anchorite** [comment]
It's a problem between the installed Gradio version and fastapi or something. 

Just have to downgrade gradio to version 4.43.0 to "fix". 

In Windows, this has to done with **Anaconda PowerShell Prompt (Miniconda)** which is included with Pinokio. Can find it using the normal windows search in the Start Menu.  Don't use cmd or MS PowerShell. 

enter:

```cd D:\pinokio\api\supir.git\app  ```

```env/Scripts/activate```

```pip install gradio==4.43.0```


and done. Should work as expected again.

**Comment by zeeyannosse** [comment]
Hello, thank you very much for the reply ! 
did everything and it was working. the only thing that remains a mystery for me is this : 
![Screenshot 2024-09-27 083125](https://github.com/user-attachments/assets/471afc20-3a13-46a6-9938-3ca27248cd61)

is it a problem the fact that > it succesfully install        " Successfully installed pip-24.2 "     and then request for an update ?                             strange isn't it ? 

  " [notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by zeeyannosse** [comment]
bhaaa > don t worry about last message.    thanks for this great video helping a lot getting overall informations ;) 
https://www.youtube.com/watch?v=OYxVEvDf284

i checked version of GIT installed > and it's tottaly ok : 
C:\Users\admin>git -v
git version 2.45.2.windows.1

again > thank you for help, and amazing development quality TOOLS ! 
bravo !

**Comment by robbsaber** [comment]
> It's a problem between the installed Gradio version and fastapi or something.
> 
> Just have to downgrade gradio to version 4.43.0 to "fix".
> 
> In Windows, this has to done with **Anaconda PowerShell Prompt (Miniconda)** which is included with Pinokio. Can find it using the normal windows search in the Start Menu. Don't use cmd or MS PowerShell.
> 
> enter:
> 
> `cd D:\pinokio\api\supir.git\app `
> 
> `env/Scripts/activate`
> 
> `pip install gradio==4.43.0`
> 
> and done. Should work as expected again.

This worked for me. Thanks!
