### ISSUE TITLE
what's wrong when i run test.py?

### ISSUE THREAD

**Issue by SeventhChat** [Fanghua-Yu/SUPIR#26]
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    model = create_SUPIR_model('options/SUPIR_v0.yaml', SUPIR_sign=args.SUPIR_sign).to(SUPIR_device)
  File "/home/sooloom/SUPIR/SUPIR/util.py", line 36, in create_SUPIR_model
    model = instantiate_from_config(config.model).cpu()
  File "/home/sooloom/SUPIR/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/sooloom/SUPIR/SUPIR/models/SUPIR_model.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/home/sooloom/SUPIR/sgm/models/diffusion.py", line 61, in __init__
    self.conditioner = instantiate_from_config(
  File "/home/sooloom/SUPIR/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/sooloom/SUPIR/sgm/modules/encoders/modules.py", line 89, in __init__
    embedder = instantiate_from_config(embconfig)
  File "/home/sooloom/SUPIR/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/sooloom/SUPIR/sgm/modules/encoders/modules.py", line 530, in __init__
    model, _, _ = open_clip.create_model_and_transforms(
  File "/home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py", line 292, in create_model_and_transforms
    model = create_model(
  File "/home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py", line 207, in create_model
    load_checkpoint(model, checkpoint_path)
  File "/home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py", line 98, in load_checkpoint
    state_dict = load_state_dict(checkpoint_path)
  File "/home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py", line 87, in load_state_dict
    checkpoint = torch.load(checkpoint_path, map_location=map_location)
  File "/home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, ' '.

**Comment by SeventhChat** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/sooloom/SUPIR/gradio_demo.py:38 in <module>                                                │
│                                                                                                  │
│    35 │   raise ValueError('Currently support CUDA only.')                                       │
│    36                                                                                            │
│    37 # load SUPIR                                                                               │
│ ❱  38 model = create_SUPIR_model('options/SUPIR_v0.yaml', SUPIR_sign='Q').to(SUPIR_device)       │
│    39 model.first_stage_model.denoise_encoder_s1 = copy.deepcopy(model.first_stage_model.denoi   │
│    40 model.current_model = 'v0-Q'                                                               │
│    41 ckpt_Q, ckpt_F = load_QF_ckpt('options/SUPIR_v0.yaml')                                     │
│                                                                                                  │
│ /home/sooloom/SUPIR/SUPIR/util.py:36 in create_SUPIR_model                                       │
│                                                                                                  │
│    33                                                                                            │
│    34 def create_SUPIR_model(config_path, SUPIR_sign=None):                                      │
│    35 │   config = OmegaConf.load(config_path)                                                   │
│ ❱  36 │   model = instantiate_from_config(config.model).cpu()                                    │
│    37 │   print(f'Loaded model config from [{config_path}]')                                     │
│    38 │   if config.SDXL_CKPT is not None:                                                       │
│    39 │   │   model.load_state_dict(load_state_dict(config.SDXL_CKPT), strict=False)             │
│                                                                                                  │
│ /home/sooloom/SUPIR/sgm/util.py:175 in instantiate_from_config                                   │
│                                                                                                  │
│   172 │   │   elif config == "__is_unconditional__":                                             │
│   173 │   │   │   return None                                                                    │
│   174 │   │   raise KeyError("Expected key `target` to instantiate.")                            │
│ ❱ 175 │   return get_obj_from_str(config["target"])(**config.get("params", dict()))              │
│   176                                                                                            │
│   177                                                                                            │
│   178 def get_obj_from_str(string, reload=False, invalidate_cache=True):                         │
│                                                                                                  │
│ /home/sooloom/SUPIR/SUPIR/models/SUPIR_model.py:13 in __init__                                   │
│                                                                                                  │
│    10                                                                                            │
│    11 class SUPIRModel(DiffusionEngine):                                                         │
│    12 │   def __init__(self, control_stage_config, ae_dtype='fp32', diffusion_dtype='fp32', p_   │
│ ❱  13 │   │   super().__init__(*args, **kwargs)                                                  │
│    14 │   │   control_model = instantiate_from_config(control_stage_config)                      │
│    15 │   │   self.model.load_control_model(control_model)                                       │
│    16 │   │   self.first_stage_model.denoise_encoder = copy.deepcopy(self.first_stage_model.en   │
│                                                                                                  │
│ /home/sooloom/SUPIR/sgm/models/diffusion.py:61 in __init__                                       │
│                                                                                                  │
│    58 │   │   │   if sampler_config is not None                                                  │
│    59 │   │   │   else None                                                                      │
│    60 │   │   )                                                                                  │
│ ❱  61 │   │   self.conditioner = instantiate_from_config(                                        │
│    62 │   │   │   default(conditioner_config, UNCONDITIONAL_CONFIG)                              │
│    63 │   │   )                                                                                  │
│    64 │   │   self.scheduler_config = scheduler_config                                           │
│                                                                                                  │
│ /home/sooloom/SUPIR/sgm/util.py:175 in instantiate_from_config                                   │
│                                                                                                  │
│   172 │   │   elif config == "__is_unconditional__":                                             │
│   173 │   │   │   return None                                                                    │
│   174 │   │   raise KeyError("Expected key `target` to instantiate.")                            │
│ ❱ 175 │   return get_obj_from_str(config["target"])(**config.get("params", dict()))              │
│   176                                                                                            │
│   177                                                                                            │
│   178 def get_obj_from_str(string, reload=False, invalidate_cache=True):                         │
│                                                                                                  │
│ /home/sooloom/SUPIR/sgm/modules/encoders/modules.py:89 in __init__                               │
│                                                                                                  │
│     86 │   │   super().__init__()                                                                │
│     87 │   │   embedders = []                                                                    │
│     88 │   │   for n, embconfig in enumerate(emb_models):                                        │
│ ❱   89 │   │   │   embedder = instantiate_from_config(embconfig)                                 │
│     90 │   │   │   assert isinstance(                                                            │
│     91 │   │   │   │   embedder, AbstractEmbModel                                                │
│     92 │   │   │   ), f"embedder model {embedder.__class__.__name__} has to inherit from Abstra  │
│                                                                                                  │
│ /home/sooloom/SUPIR/sgm/util.py:175 in instantiate_from_config                                   │
│                                                                                                  │
│   172 │   │   elif config == "__is_unconditional__":                                             │
│   173 │   │   │   return None                                                                    │
│   174 │   │   raise KeyError("Expected key `target` to instantiate.")                            │
│ ❱ 175 │   return get_obj_from_str(config["target"])(**config.get("params", dict()))              │
│   176                                                                                            │
│   177                                                                                            │
│   178 def get_obj_from_str(string, reload=False, invalidate_cache=True):                         │
│                                                                                                  │
│ /home/sooloom/SUPIR/sgm/modules/encoders/modules.py:530 in __init__                              │
│                                                                                                  │
│    527 │   ):                                                                                    │
│    528 │   │   super().__init__()                                                                │
│    529 │   │   assert layer in self.LAYERS                                                       │
│ ❱  530 │   │   model, _, _ = open_clip.create_model_and_transforms(                              │
│    531 │   │   │   arch,                                                                         │
│    532 │   │   │   device=torch.device("cpu"),                                                   │
│    533 │   │   │   pretrained=version if SDXL_CLIP2_CKPT_PTH is None else SDXL_CLIP2_CKPT_PTH,   │
│                                                                                                  │
│ /home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py:292 in      │
│ create_model_and_transforms                                                                      │
│                                                                                                  │
│   289 │   │   cache_dir: Optional[str] = None,                                                   │
│   290 │   │   output_dict: Optional[bool] = None,                                                │
│   291 ):                                                                                         │
│ ❱ 292 │   model = create_model(                                                                  │
│   293 │   │   model_name,                                                                        │
│   294 │   │   pretrained,                                                                        │
│   295 │   │   precision=precision,                                                               │
│                                                                                                  │
│ /home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py:207 in      │
│ create_model                                                                                     │
│                                                                                                  │
│   204 │   │   │                                                                                  │
│   205 │   │   │   if checkpoint_path:                                                            │
│   206 │   │   │   │   logging.info(f'Loading pretrained {model_name} weights ({pretrained}).')   │
│ ❱ 207 │   │   │   │   load_checkpoint(model, checkpoint_path)                                    │
│   208 │   │   │   else:                                                                          │
│   209 │   │   │   │   error_str = (                                                              │
│   210 │   │   │   │   │   f'Pretrained weights ({pretrained}) not found for model {model_name}   │
│                                                                                                  │
│ /home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py:98 in       │
│ load_checkpoint                                                                                  │
│                                                                                                  │
│    95                                                                                            │
│    96                                                                                            │
│    97 def load_checkpoint(model, checkpoint_path, strict=True):                                  │
│ ❱  98 │   state_dict = load_state_dict(checkpoint_path)                                          │
│    99 │   # detect old format and make compatible with new format                                │
│   100 │   if 'positional_embedding' in state_dict and not hasattr(model, 'positional_embedding   │
│   101 │   │   state_dict = convert_to_custom_text_state_dict(state_dict)                         │
│                                                                                                  │
│ /home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/open_clip/factory.py:87 in       │
│ load_state_dict                                                                                  │
│                                                                                                  │
│    84                                                                                            │
│    85                                                                                            │
│    86 def load_state_dict(checkpoint_path: str, map_location='cpu'):                             │
│ ❱  87 │   checkpoint = torch.load(checkpoint_path, map_location=map_location)                    │
│    88 │   if isinstance(checkpoint, dict) and 'state_dict' in checkpoint:                        │
│    89 │   │   state_dict = checkpoint['state_dict']                                              │
│    90 │   else:                                                                                  │
│                                                                                                  │
│ /home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/torch/serialization.py:1028 in   │
│ load                                                                                             │
│                                                                                                  │
│   1025 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │
│   1026 │   │   │   except RuntimeError as e:                                                     │
│   1027 │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None           │
│ ❱ 1028 │   │   return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args  │
│   1029                                                                                           │
│   1030                                                                                           │
│   1031 # Register pickling support for layout instances such as                                  │
│                                                                                                  │
│ /home/sooloom/miniconda3/envs/SUPIR/lib/python3.8/site-packages/torch/serialization.py:1245 in   │
│ _legacy_load                                                                                     │
│                                                                                                  │
│   1242 │   │   │   "torch.load 不适用于未在Python上实现readinto的类文件对象 3.8.0 和 3.8.1. "    │
│   1243 │   │   │   f"接收到类型为的对象 \"{type(f)}\". 请更新到 Python 3.8.2 或更新以恢复此功能  │
│   1244 │                                                                                         │
│ ❱ 1245 │   magic_number = pickle_module.load(f, **pickle_load_args)                              │
│   1246 │   if magic_number != MAGIC_NUMBER:                                                      │
│   1247 │   │   raise RuntimeError("无效的幻数;损坏的文件?")                                      │
│   1248 │   protocol_version = pickle_module.load(f, **pickle_load_args)                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnpicklingError: invalid load key, ' '.
