### ISSUE TITLE
Server port error

### ISSUE THREAD

**Issue by ZephyrusXI** [Fanghua-Yu/SUPIR#55]
I keep getting server port error after hours into the initial run. There is no other process taking up the port and I've tried a reboot.

`Traceback (most recent call last):
  File "D:\Downloads\sd.webui\SUPIR\gradio_demo.py", line 307, in <module>
    block.launch(server_name=server_ip, server_port=server_port)
  File "D:\Downloads\sd.webui\SUPIR\venv\lib\site-packages\gradio\blocks.py", line 1998, in launch
    ) = networking.start_server(
  File "D:\Downloads\sd.webui\SUPIR\venv\lib\site-packages\gradio\networking.py", line 207, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 6688-6688. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.`

**Comment by FurkanGozukara** [comment]
just remove port from gradio it will use default 7860 or next one
