### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by hkarakose** [Fanghua-Yu/SUPIR#7]
I encountered an error while experimenting this project.

```
Traceback (most recent call last):
  File "gradio_demo.py", line 20, in <module>
    model = create_SUPIR_model('options/SUPIR_v0.yaml').to(SUPIR_device)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 54, in to
    return super().to(*args, **kwargs)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/anaconda3/envs/SUPIR/lib/python3.8/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

However Nvidia does not provide CUDA for macOS: https://developer.nvidia.com/cuda-downloads

So, does it mean, this project does not support Linux?

**Comment by xiaom233** [comment]
Sorry for that, but this project only supports Linux. We may develop a MacOS version in the future.

**Comment by brayevalerien** [comment]
I struggled with Windows aswell but I think I got it working. Unfortunatly I dont have enough memory to load the pretrained models, but I'll soon update to 128Gb of ram, I'll keep this issue updated if it works on Windows
